
version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
    post_build:
        commands:
            - echo "we are in the post build phase"
artifacts:
  files:
    - '**/*'
   name: lostandfound-be-artifacts